# Generated by Django 4.2.7 on 2023-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='col',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='tag',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
