# Generated by Django 4.2.7 on 2023-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_column_remove_player_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='column',
            new_name='col',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tag',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='value',
            field=models.IntegerField(),
        ),
    ]
