# Generated by Django 4.2.7 on 2023-11-18 00:37

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_board_player_alter_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='col',
            field=models.IntegerField(validators=[game.models.validate_col_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=1, validators=[game.models.validate_unique_name]),
        ),
        migrations.AlterField(
            model_name='player',
            name='row',
            field=models.IntegerField(validators=[game.models.validate_row_range]),
        ),
    ]
