# Generated by Django 4.2.7 on 2023-11-24 04:27

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_col_alter_player_name_alter_player_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='col',
            field=models.IntegerField(validators=[game.models.validate_col_range]),
        ),
        migrations.AlterField(
            model_name='board',
            name='row',
            field=models.IntegerField(validators=[game.models.validate_row_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(),
        ),
    ]
